### ISSUE TITLE
Input validation icons should not overlap placeholders 

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdEditor#338]
Placeholder input text can be padded and use `ellipsis` when exceeding the input width.

Example styling for inputs:
```css
input[placeholder] {
    text-overflow: ellipsis;
    padding-right: 30px;
}
```

![image](https://user-images.githubusercontent.com/5833603/65807255-f4ebf280-e139-11e9-9862-39eaa1834745.png)
