### ISSUE TITLE
Add version(dev) badge?

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdEditor#50]
Something like this (could use the version instead when we have a release):

``` css
li.sidebar-brand::after {
    content: 'dev';
    color: orange;
    font-variant: small-caps;
    font-size: .75em;
    position: relative;
    top: -7px;
}
```

![image](https://cloud.githubusercontent.com/assets/5833603/19332394/099def58-9098-11e6-8021-8f5c9f1d92b0.png)
